name: Deploy Shinylive App

# O script vai rodar toda vez que você atualizar a branch main
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch: # Permite rodar o script manualmente clicando num botão no GitHub

# Permissões necessárias para publicar no GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Instalar o R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Instalar pacotes necessários
        run: |
          install.packages(c("shinylive", "httpuv"))
        shell: Rscript {0}

      - name: Compilar aplicativo para WebAssembly (Shinylive)
        run: |
          # Ele pega a pasta "app" e compila na pasta "site_offline"
          shinylive::export(appdir = "app", destdir = "site_offline")
        shell: Rscript {0}

      - name: Fazer upload dos artefatos estáticos
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'site_offline'

      - name: Publicar no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
